# Generated by Django 4.0.4 on 2022-06-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibercat', '0002_caruselslider_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestseller',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='novelty',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='caruselslider',
            name='carusel_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='caruselslider',
            name='carusel_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
    ]
