# Generated by Django 4.0.4 on 2022-06-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibercat', '0003_product_bestseller_product_novelty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
