# Generated by Django 4.0.4 on 2022-07-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibercat', '0005_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='group',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Группа'),
        ),
    ]
