# Generated by Django 4.0.4 on 2022-07-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibercat', '0006_productcategory_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default=5, verbose_name='Рейтинг'),
        ),
    ]
