# Generated by Django 4.0.4 on 2022-07-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibercat', '0007_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image_on_main',
            field=models.ImageField(blank=True, upload_to='products_images/Catalog', verbose_name='Фото'),
        ),
    ]
