# Generated by Django 4.0.4 on 2022-07-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibercat', '0008_productcategory_image_on_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='caruselslider',
            name='url',
            field=models.SlugField(blank=True, max_length=200, verbose_name='URL'),
        ),
    ]
