# Generated by Django 4.0.4 on 2022-07-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibercat', '0009_caruselslider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caruselslider',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='URL'),
        ),
    ]
