# Generated by Django 4.0.4 on 2022-07-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kibercat', '0010_alter_caruselslider_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/Brands/', verbose_name='Фото')),
                ('brands', models.CharField(db_index=True, max_length=64, verbose_name='Название')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='kibercat.product')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
